services:
    armory:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/data/
            - ./logs:/logs/
        env_file:
            - .env
        ports:
            - 7000:48733
